// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: appointments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAppointment = `-- name: CreateAppointment :one
INSERT INTO appointments (patient_id, provider_id, facility_id, start_at, end_at, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, patient_id, provider_id, facility_id, start_at, end_at, status, reason, reminder_sent_at, created_at, updated_at
`

type CreateAppointmentParams struct {
	PatientID  pgtype.UUID        `json:"patient_id"`
	ProviderID pgtype.UUID        `json:"provider_id"`
	FacilityID pgtype.UUID        `json:"facility_id"`
	StartAt    pgtype.Timestamptz `json:"start_at"`
	EndAt      pgtype.Timestamptz `json:"end_at"`
	Reason     pgtype.Text        `json:"reason"`
}

func (q *Queries) CreateAppointment(ctx context.Context, arg CreateAppointmentParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, createAppointment,
		arg.PatientID,
		arg.ProviderID,
		arg.FacilityID,
		arg.StartAt,
		arg.EndAt,
		arg.Reason,
	)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ProviderID,
		&i.FacilityID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.Reason,
		&i.ReminderSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAvailability = `-- name: CreateAvailability :one
INSERT INTO provider_availability (provider_id, weekday, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, provider_id, weekday, start_time, end_time, created_at
`

type CreateAvailabilityParams struct {
	ProviderID pgtype.UUID `json:"provider_id"`
	Weekday    int16       `json:"weekday"`
	StartTime  pgtype.Time `json:"start_time"`
	EndTime    pgtype.Time `json:"end_time"`
}

func (q *Queries) CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (ProviderAvailability, error) {
	row := q.db.QueryRow(ctx, createAvailability,
		arg.ProviderID,
		arg.Weekday,
		arg.StartTime,
		arg.EndTime,
	)
	var i ProviderAvailability
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Weekday,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAvailability = `-- name: DeleteAvailability :exec
DELETE FROM provider_availability WHERE id = $1 AND provider_id = $2
`

type DeleteAvailabilityParams struct {
	ID         pgtype.UUID `json:"id"`
	ProviderID pgtype.UUID `json:"provider_id"`
}

// Scoped to the owning provider so one provider can't delete another's
// availability row — see appointments.Service.DeleteAvailability.
func (q *Queries) DeleteAvailability(ctx context.Context, arg DeleteAvailabilityParams) error {
	_, err := q.db.Exec(ctx, deleteAvailability, arg.ID, arg.ProviderID)
	return err
}

const findAppointmentByID = `-- name: FindAppointmentByID :one
SELECT id, patient_id, provider_id, facility_id, start_at, end_at, status, reason, reminder_sent_at, created_at, updated_at FROM appointments WHERE id = $1
`

func (q *Queries) FindAppointmentByID(ctx context.Context, id pgtype.UUID) (Appointment, error) {
	row := q.db.QueryRow(ctx, findAppointmentByID, id)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ProviderID,
		&i.FacilityID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.Reason,
		&i.ReminderSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAppointmentsForPatient = `-- name: ListAppointmentsForPatient :many
SELECT id, patient_id, provider_id, facility_id, start_at, end_at, status, reason, reminder_sent_at, created_at, updated_at FROM appointments WHERE patient_id = $1 ORDER BY start_at DESC
`

func (q *Queries) ListAppointmentsForPatient(ctx context.Context, patientID pgtype.UUID) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointmentsForPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.ProviderID,
			&i.FacilityID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.Reason,
			&i.ReminderSentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAppointmentsForProviderInRange = `-- name: ListAppointmentsForProviderInRange :many
SELECT id, patient_id, provider_id, facility_id, start_at, end_at, status, reason, reminder_sent_at, created_at, updated_at FROM appointments
WHERE provider_id = $1
  AND start_at < $3
  AND end_at > $2
  AND status != 'cancelled'
ORDER BY start_at
`

type ListAppointmentsForProviderInRangeParams struct {
	ProviderID pgtype.UUID        `json:"provider_id"`
	EndAt      pgtype.Timestamptz `json:"end_at"`
	StartAt    pgtype.Timestamptz `json:"start_at"`
}

// Overlap check: any appointment that isn't cancelled whose interval
// intersects [range_start, range_end). Used both for slot-generation's
// overlap filter and for a provider's own calendar view.
func (q *Queries) ListAppointmentsForProviderInRange(ctx context.Context, arg ListAppointmentsForProviderInRangeParams) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listAppointmentsForProviderInRange, arg.ProviderID, arg.EndAt, arg.StartAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.ProviderID,
			&i.FacilityID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.Reason,
			&i.ReminderSentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityForProvider = `-- name: ListAvailabilityForProvider :many
SELECT id, provider_id, weekday, start_time, end_time, created_at FROM provider_availability
WHERE provider_id = $1
ORDER BY weekday, start_time
`

func (q *Queries) ListAvailabilityForProvider(ctx context.Context, providerID pgtype.UUID) ([]ProviderAvailability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityForProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProviderAvailability
	for rows.Next() {
		var i ProviderAvailability
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Weekday,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingUnreminded = `-- name: ListUpcomingUnreminded :many
SELECT id, patient_id, provider_id, facility_id, start_at, end_at, status, reason, reminder_sent_at, created_at, updated_at FROM appointments
WHERE status IN ('scheduled', 'confirmed')
  AND reminder_sent_at IS NULL
  AND start_at BETWEEN now() AND now() + interval '24 hours'
`

func (q *Queries) ListUpcomingUnreminded(ctx context.Context) ([]Appointment, error) {
	rows, err := q.db.Query(ctx, listUpcomingUnreminded)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Appointment
	for rows.Next() {
		var i Appointment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.ProviderID,
			&i.FacilityID,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.Reason,
			&i.ReminderSentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReminderSent = `-- name: MarkReminderSent :exec
UPDATE appointments SET reminder_sent_at = now() WHERE id = $1
`

func (q *Queries) MarkReminderSent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markReminderSent, id)
	return err
}

const updateAppointmentStatus = `-- name: UpdateAppointmentStatus :one
UPDATE appointments
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, patient_id, provider_id, facility_id, start_at, end_at, status, reason, reminder_sent_at, created_at, updated_at
`

type UpdateAppointmentStatusParams struct {
	ID     pgtype.UUID       `json:"id"`
	Status AppointmentStatus `json:"status"`
}

func (q *Queries) UpdateAppointmentStatus(ctx context.Context, arg UpdateAppointmentStatusParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointmentStatus, arg.ID, arg.Status)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ProviderID,
		&i.FacilityID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.Reason,
		&i.ReminderSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAppointmentTime = `-- name: UpdateAppointmentTime :one
UPDATE appointments
SET start_at = $2,
    end_at = $3,
    status = 'scheduled',
    updated_at = now()
WHERE id = $1
  AND status NOT IN ('cancelled', 'completed')
RETURNING id, patient_id, provider_id, facility_id, start_at, end_at, status, reason, reminder_sent_at, created_at, updated_at
`

type UpdateAppointmentTimeParams struct {
	ID      pgtype.UUID        `json:"id"`
	StartAt pgtype.Timestamptz `json:"start_at"`
	EndAt   pgtype.Timestamptz `json:"end_at"`
}

// Reschedule: sets status back to 'scheduled' unless it was already
// cancelled/completed, in which case the WHERE guard means zero rows
// match and the repository surfaces ErrAppointmentNotFound.
func (q *Queries) UpdateAppointmentTime(ctx context.Context, arg UpdateAppointmentTimeParams) (Appointment, error) {
	row := q.db.QueryRow(ctx, updateAppointmentTime, arg.ID, arg.StartAt, arg.EndAt)
	var i Appointment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ProviderID,
		&i.FacilityID,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.Reason,
		&i.ReminderSentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
