// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (patient_id, encounter_id, uploaded_by, file_key, filename, mime_type, size, version, root_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, patient_id, encounter_id, uploaded_by, file_key, filename, mime_type, size, version, root_id, created_at
`

type CreateAttachmentParams struct {
	PatientID   pgtype.UUID `json:"patient_id"`
	EncounterID pgtype.UUID `json:"encounter_id"`
	UploadedBy  pgtype.UUID `json:"uploaded_by"`
	FileKey     string      `json:"file_key"`
	Filename    string      `json:"filename"`
	MimeType    string      `json:"mime_type"`
	Size        int64       `json:"size"`
	Version     int32       `json:"version"`
	RootID      pgtype.UUID `json:"root_id"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.PatientID,
		arg.EncounterID,
		arg.UploadedBy,
		arg.FileKey,
		arg.Filename,
		arg.MimeType,
		arg.Size,
		arg.Version,
		arg.RootID,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.EncounterID,
		&i.UploadedBy,
		&i.FileKey,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.Version,
		&i.RootID,
		&i.CreatedAt,
	)
	return i, err
}

const findAttachmentByID = `-- name: FindAttachmentByID :one
SELECT id, patient_id, encounter_id, uploaded_by, file_key, filename, mime_type, size, version, root_id, created_at FROM attachments WHERE id = $1
`

func (q *Queries) FindAttachmentByID(ctx context.Context, id pgtype.UUID) (Attachment, error) {
	row := q.db.QueryRow(ctx, findAttachmentByID, id)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.EncounterID,
		&i.UploadedBy,
		&i.FileKey,
		&i.Filename,
		&i.MimeType,
		&i.Size,
		&i.Version,
		&i.RootID,
		&i.CreatedAt,
	)
	return i, err
}

const findMaxAttachmentVersionByRoot = `-- name: FindMaxAttachmentVersionByRoot :one
SELECT COALESCE(MAX(version), 0)::int AS max_version
FROM attachments
WHERE COALESCE(root_id, id) = $1
`

func (q *Queries) FindMaxAttachmentVersionByRoot(ctx context.Context, rootID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, findMaxAttachmentVersionByRoot, rootID)
	var max_version int32
	err := row.Scan(&max_version)
	return max_version, err
}

const listAttachmentVersionsByRoot = `-- name: ListAttachmentVersionsByRoot :many
SELECT id, patient_id, encounter_id, uploaded_by, file_key, filename, mime_type, size, version, root_id, created_at FROM attachments
WHERE COALESCE(root_id, id) = $1
ORDER BY version
`

// rootID must already be resolved to the true root (the id shared by
// COALESCE(root_id, id) across the whole lineage) — see
// Service.resolveRootID.
func (q *Queries) ListAttachmentVersionsByRoot(ctx context.Context, rootID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listAttachmentVersionsByRoot, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.EncounterID,
			&i.UploadedBy,
			&i.FileKey,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.Version,
			&i.RootID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestAttachmentsByPatient = `-- name: ListLatestAttachmentsByPatient :many
SELECT DISTINCT ON (COALESCE(root_id, id)) id, patient_id, encounter_id, uploaded_by, file_key, filename, mime_type, size, version, root_id, created_at
FROM attachments
WHERE patient_id = $1
ORDER BY COALESCE(root_id, id), version DESC
`

// One row per logical document — the highest-version row within each
// root_id/id lineage (COALESCE(root_id, id) groups a root row together with
// every version that points back at it).
func (q *Queries) ListLatestAttachmentsByPatient(ctx context.Context, patientID pgtype.UUID) ([]Attachment, error) {
	rows, err := q.db.Query(ctx, listLatestAttachmentsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.EncounterID,
			&i.UploadedBy,
			&i.FileKey,
			&i.Filename,
			&i.MimeType,
			&i.Size,
			&i.Version,
			&i.RootID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
