// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :one
INSERT INTO audit_log (actor_user_id, actor_role, action, resource_type, resource_id, patient_id, result, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, actor_user_id, actor_role, action, resource_type, resource_id, patient_id, result, metadata, occurred_at
`

type InsertAuditLogParams struct {
	ActorUserID  pgtype.UUID `json:"actor_user_id"`
	ActorRole    UserRole    `json:"actor_role"`
	Action       string      `json:"action"`
	ResourceType string      `json:"resource_type"`
	ResourceID   pgtype.UUID `json:"resource_id"`
	PatientID    pgtype.UUID `json:"patient_id"`
	Result       AuditResult `json:"result"`
	Metadata     []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditLog,
		arg.ActorUserID,
		arg.ActorRole,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.PatientID,
		arg.Result,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.ActorRole,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.PatientID,
		&i.Result,
		&i.Metadata,
		&i.OccurredAt,
	)
	return i, err
}

const listAuditLogForPatient = `-- name: ListAuditLogForPatient :many
SELECT id, actor_user_id, actor_role, action, resource_type, resource_id, patient_id, result, metadata, occurred_at FROM audit_log WHERE patient_id = $1 ORDER BY occurred_at DESC
`

func (q *Queries) ListAuditLogForPatient(ctx context.Context, patientID pgtype.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogForPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorRole,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.PatientID,
			&i.Result,
			&i.Metadata,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
