// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authz.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (name, description, full_access)
VALUES ($1, $2, $3)
RETURNING id, name, description, full_access, created_at, updated_at
`

type CreateRoleParams struct {
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	FullAccess  bool        `json:"full_access"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Name, arg.Description, arg.FullAccess)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FullAccess,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const findRoleByID = `-- name: FindRoleByID :one
SELECT id, name, description, full_access, created_at, updated_at FROM roles WHERE id = $1
`

func (q *Queries) FindRoleByID(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, findRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FullAccess,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserWithRoleByID = `-- name: FindUserWithRoleByID :one
SELECT u.id, u.email, u.phone, u.role, u.status, u.created_at, u.role_id, u.full_name, r.name AS role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.id = $1
`

type FindUserWithRoleByIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Role      UserRole           `json:"role"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RoleID    pgtype.UUID        `json:"role_id"`
	FullName  pgtype.Text        `json:"full_name"`
	RoleName  pgtype.Text        `json:"role_name"`
}

func (q *Queries) FindUserWithRoleByID(ctx context.Context, id pgtype.UUID) (FindUserWithRoleByIDRow, error) {
	row := q.db.QueryRow(ctx, findUserWithRoleByID, id)
	var i FindUserWithRoleByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.RoleID,
		&i.FullName,
		&i.RoleName,
	)
	return i, err
}

const getUserAccess = `-- name: GetUserAccess :one
SELECT r.id AS role_id, r.full_access
FROM users u
JOIN roles r ON u.role_id = r.id
WHERE u.id = $1
`

type GetUserAccessRow struct {
	RoleID     pgtype.UUID `json:"role_id"`
	FullAccess bool        `json:"full_access"`
}

func (q *Queries) GetUserAccess(ctx context.Context, id pgtype.UUID) (GetUserAccessRow, error) {
	row := q.db.QueryRow(ctx, getUserAccess, id)
	var i GetUserAccessRow
	err := row.Scan(&i.RoleID, &i.FullAccess)
	return i, err
}

const insertRolePermissions = `-- name: InsertRolePermissions :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT $1, unnest($2::uuid[])
`

type InsertRolePermissionsParams struct {
	RoleID  pgtype.UUID   `json:"role_id"`
	Column2 []pgtype.UUID `json:"column_2"`
}

func (q *Queries) InsertRolePermissions(ctx context.Context, arg InsertRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, insertRolePermissions, arg.RoleID, arg.Column2)
	return err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, resource, action FROM permissions ORDER BY resource, action
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Resource, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsForRole = `-- name: ListPermissionsForRole :many
SELECT p.id, p.resource, p.action
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = $1
ORDER BY p.resource, p.action
`

func (q *Queries) ListPermissionsForRole(ctx context.Context, roleID pgtype.UUID) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsForRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(&i.ID, &i.Resource, &i.Action); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, full_access, created_at, updated_at FROM roles ORDER BY name
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.FullAccess,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithRole = `-- name: ListUsersWithRole :many
SELECT u.id, u.email, u.phone, u.role, u.status, u.created_at, u.role_id, u.full_name, r.name AS role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
ORDER BY u.created_at DESC
`

type ListUsersWithRoleRow struct {
	ID        pgtype.UUID        `json:"id"`
	Email     pgtype.Text        `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Role      UserRole           `json:"role"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RoleID    pgtype.UUID        `json:"role_id"`
	FullName  pgtype.Text        `json:"full_name"`
	RoleName  pgtype.Text        `json:"role_name"`
}

func (q *Queries) ListUsersWithRole(ctx context.Context) ([]ListUsersWithRoleRow, error) {
	rows, err := q.db.Query(ctx, listUsersWithRole)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersWithRoleRow
	for rows.Next() {
		var i ListUsersWithRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.RoleID,
			&i.FullName,
			&i.RoleName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceRolePermissions = `-- name: ReplaceRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) ReplaceRolePermissions(ctx context.Context, roleID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, replaceRolePermissions, roleID)
	return err
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
SET name = $2, description = $3, full_access = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, description, full_access, created_at, updated_at
`

type UpdateRoleParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	FullAccess  bool        `json:"full_access"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.FullAccess,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FullAccess,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRoleID = `-- name: UpdateUserRoleID :one
UPDATE users SET role_id = $2, updated_at = now() WHERE id = $1
RETURNING id, email, phone, password_hash, role, status, created_at, updated_at, role_id, verified_at, full_name
`

type UpdateUserRoleIDParams struct {
	ID     pgtype.UUID `json:"id"`
	RoleID pgtype.UUID `json:"role_id"`
}

func (q *Queries) UpdateUserRoleID(ctx context.Context, arg UpdateUserRoleIDParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRoleID, arg.ID, arg.RoleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
		&i.VerifiedAt,
		&i.FullName,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2, updated_at = now() WHERE id = $1
RETURNING id, email, phone, password_hash, role, status, created_at, updated_at, role_id, verified_at, full_name
`

type UpdateUserStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
		&i.VerifiedAt,
		&i.FullName,
	)
	return i, err
}
