// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consults.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingConsultsForProvider = `-- name: CountPendingConsultsForProvider :one
SELECT count(*) FROM consultations
WHERE target_provider_id = $1::uuid AND status = 'requested'
`

// Consultations where provider_id is the target and awaiting their first
// reply — used by the physician-specific dashboard view (see
// dashboard.Summary.PendingConsultCount).
func (q *Queries) CountPendingConsultsForProvider(ctx context.Context, providerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingConsultsForProvider, providerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConsultation = `-- name: CreateConsultation :one
INSERT INTO consultations (
    patient_id, requesting_provider_id, target_provider_id, reason
)
VALUES ($1, $2, $3, $4)
RETURNING id, patient_id, requesting_provider_id, target_provider_id, reason, status, created_at, updated_at
`

type CreateConsultationParams struct {
	PatientID            pgtype.UUID `json:"patient_id"`
	RequestingProviderID pgtype.UUID `json:"requesting_provider_id"`
	TargetProviderID     pgtype.UUID `json:"target_provider_id"`
	Reason               string      `json:"reason"`
}

func (q *Queries) CreateConsultation(ctx context.Context, arg CreateConsultationParams) (Consultation, error) {
	row := q.db.QueryRow(ctx, createConsultation,
		arg.PatientID,
		arg.RequestingProviderID,
		arg.TargetProviderID,
		arg.Reason,
	)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.RequestingProviderID,
		&i.TargetProviderID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createConsultationMessage = `-- name: CreateConsultationMessage :one
INSERT INTO consultation_messages (
    consultation_id, sender_id, body, attachment_ids
)
VALUES ($1, $2, $3, $4)
RETURNING id, consultation_id, sender_id, body, attachment_ids, created_at
`

type CreateConsultationMessageParams struct {
	ConsultationID pgtype.UUID   `json:"consultation_id"`
	SenderID       pgtype.UUID   `json:"sender_id"`
	Body           string        `json:"body"`
	AttachmentIds  []pgtype.UUID `json:"attachment_ids"`
}

func (q *Queries) CreateConsultationMessage(ctx context.Context, arg CreateConsultationMessageParams) (ConsultationMessage, error) {
	row := q.db.QueryRow(ctx, createConsultationMessage,
		arg.ConsultationID,
		arg.SenderID,
		arg.Body,
		arg.AttachmentIds,
	)
	var i ConsultationMessage
	err := row.Scan(
		&i.ID,
		&i.ConsultationID,
		&i.SenderID,
		&i.Body,
		&i.AttachmentIds,
		&i.CreatedAt,
	)
	return i, err
}

const findConsultationByID = `-- name: FindConsultationByID :one
SELECT id, patient_id, requesting_provider_id, target_provider_id, reason, status, created_at, updated_at FROM consultations WHERE id = $1
`

func (q *Queries) FindConsultationByID(ctx context.Context, id pgtype.UUID) (Consultation, error) {
	row := q.db.QueryRow(ctx, findConsultationByID, id)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.RequestingProviderID,
		&i.TargetProviderID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllConsultations = `-- name: ListAllConsultations :many
SELECT id, patient_id, requesting_provider_id, target_provider_id, reason, status, created_at, updated_at FROM consultations ORDER BY updated_at DESC
`

// Platform-wide oversight listing — system_admin has no provider identity
// to scope ListConsultationsForProvider by, so its inbox view needs an
// unscoped list instead.
func (q *Queries) ListAllConsultations(ctx context.Context) ([]Consultation, error) {
	rows, err := q.db.Query(ctx, listAllConsultations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consultation
	for rows.Next() {
		var i Consultation
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.RequestingProviderID,
			&i.TargetProviderID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsultationMessages = `-- name: ListConsultationMessages :many
SELECT id, consultation_id, sender_id, body, attachment_ids, created_at FROM consultation_messages WHERE consultation_id = $1 ORDER BY created_at
`

func (q *Queries) ListConsultationMessages(ctx context.Context, consultationID pgtype.UUID) ([]ConsultationMessage, error) {
	rows, err := q.db.Query(ctx, listConsultationMessages, consultationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsultationMessage
	for rows.Next() {
		var i ConsultationMessage
		if err := rows.Scan(
			&i.ID,
			&i.ConsultationID,
			&i.SenderID,
			&i.Body,
			&i.AttachmentIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsultationsForProvider = `-- name: ListConsultationsForProvider :many
SELECT id, patient_id, requesting_provider_id, target_provider_id, reason, status, created_at, updated_at FROM consultations
WHERE requesting_provider_id = $1 OR target_provider_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListConsultationsForProvider(ctx context.Context, requestingProviderID pgtype.UUID) ([]Consultation, error) {
	rows, err := q.db.Query(ctx, listConsultationsForProvider, requestingProviderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consultation
	for rows.Next() {
		var i Consultation
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.RequestingProviderID,
			&i.TargetProviderID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchAllConsultations = `-- name: SearchAllConsultations :many
SELECT id, patient_id, requesting_provider_id, target_provider_id, reason, status, created_at, updated_at FROM consultations
WHERE reason ILIKE '%' || $1::text || '%'
ORDER BY similarity(reason, $1::text) DESC, updated_at DESC
LIMIT $2::int
`

type SearchAllConsultationsParams struct {
	Query       string `json:"query"`
	ResultLimit int32  `json:"result_limit"`
}

// Text-filtered variant of ListAllConsultations — system_admin oversight
// only, same as its unfiltered counterpart.
func (q *Queries) SearchAllConsultations(ctx context.Context, arg SearchAllConsultationsParams) ([]Consultation, error) {
	rows, err := q.db.Query(ctx, searchAllConsultations, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consultation
	for rows.Next() {
		var i Consultation
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.RequestingProviderID,
			&i.TargetProviderID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchConsultationsForProvider = `-- name: SearchConsultationsForProvider :many
SELECT id, patient_id, requesting_provider_id, target_provider_id, reason, status, created_at, updated_at FROM consultations
WHERE (requesting_provider_id = $1::uuid OR target_provider_id = $1::uuid)
  AND reason ILIKE '%' || $2::text || '%'
ORDER BY similarity(reason, $2::text) DESC, updated_at DESC
LIMIT $3::int
`

type SearchConsultationsForProviderParams struct {
	ProviderID  pgtype.UUID `json:"provider_id"`
	Query       string      `json:"query"`
	ResultLimit int32       `json:"result_limit"`
}

// Text-filtered variant of ListConsultationsForProvider — same
// requesting-or-target-provider scoping, just with a reason ILIKE filter
// added, so search never surfaces a consultation the caller isn't already
// a party to.
func (q *Queries) SearchConsultationsForProvider(ctx context.Context, arg SearchConsultationsForProviderParams) ([]Consultation, error) {
	rows, err := q.db.Query(ctx, searchConsultationsForProvider, arg.ProviderID, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Consultation
	for rows.Next() {
		var i Consultation
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.RequestingProviderID,
			&i.TargetProviderID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConsultationStatus = `-- name: UpdateConsultationStatus :one
UPDATE consultations
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, patient_id, requesting_provider_id, target_provider_id, reason, status, created_at, updated_at
`

type UpdateConsultationStatusParams struct {
	ID     pgtype.UUID   `json:"id"`
	Status ConsultStatus `json:"status"`
}

func (q *Queries) UpdateConsultationStatus(ctx context.Context, arg UpdateConsultationStatusParams) (Consultation, error) {
	row := q.db.QueryRow(ctx, updateConsultationStatus, arg.ID, arg.Status)
	var i Consultation
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.RequestingProviderID,
		&i.TargetProviderID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
