// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consent.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConsentGrant = `-- name: CreateConsentGrant :one
INSERT INTO consent_grants (patient_id, grantee_type, grantee_id, scope, scope_ref, granted_via, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, patient_id, grantee_type, grantee_id, scope, scope_ref, status, granted_via, granted_at, revoked_at, expires_at
`

type CreateConsentGrantParams struct {
	PatientID   pgtype.UUID        `json:"patient_id"`
	GranteeType ConsentGranteeType `json:"grantee_type"`
	GranteeID   pgtype.UUID        `json:"grantee_id"`
	Scope       ConsentScope       `json:"scope"`
	ScopeRef    pgtype.UUID        `json:"scope_ref"`
	GrantedVia  ConsentGrantedVia  `json:"granted_via"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateConsentGrant(ctx context.Context, arg CreateConsentGrantParams) (ConsentGrant, error) {
	row := q.db.QueryRow(ctx, createConsentGrant,
		arg.PatientID,
		arg.GranteeType,
		arg.GranteeID,
		arg.Scope,
		arg.ScopeRef,
		arg.GrantedVia,
		arg.ExpiresAt,
	)
	var i ConsentGrant
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.GranteeType,
		&i.GranteeID,
		&i.Scope,
		&i.ScopeRef,
		&i.Status,
		&i.GrantedVia,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const findActiveGrants = `-- name: FindActiveGrants :many
SELECT id, patient_id, grantee_type, grantee_id, scope, scope_ref, status, granted_via, granted_at, revoked_at, expires_at FROM consent_grants
WHERE patient_id = $1
  AND status = 'active'
  AND (expires_at IS NULL OR expires_at > now())
  AND (
    (grantee_type = 'provider' AND grantee_id = $2) OR
    (grantee_type = 'facility' AND grantee_id = $3)
  )
`

type FindActiveGrantsParams struct {
	PatientID   pgtype.UUID `json:"patient_id"`
	GranteeID   pgtype.UUID `json:"grantee_id"`
	GranteeID_2 pgtype.UUID `json:"grantee_id_2"`
}

func (q *Queries) FindActiveGrants(ctx context.Context, arg FindActiveGrantsParams) ([]ConsentGrant, error) {
	rows, err := q.db.Query(ctx, findActiveGrants, arg.PatientID, arg.GranteeID, arg.GranteeID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsentGrant
	for rows.Next() {
		var i ConsentGrant
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.GranteeType,
			&i.GranteeID,
			&i.Scope,
			&i.ScopeRef,
			&i.Status,
			&i.GrantedVia,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsentGrantsForPatient = `-- name: ListConsentGrantsForPatient :many
SELECT id, patient_id, grantee_type, grantee_id, scope, scope_ref, status, granted_via, granted_at, revoked_at, expires_at FROM consent_grants WHERE patient_id = $1 ORDER BY granted_at DESC
`

func (q *Queries) ListConsentGrantsForPatient(ctx context.Context, patientID pgtype.UUID) ([]ConsentGrant, error) {
	rows, err := q.db.Query(ctx, listConsentGrantsForPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConsentGrant
	for rows.Next() {
		var i ConsentGrant
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.GranteeType,
			&i.GranteeID,
			&i.Scope,
			&i.ScopeRef,
			&i.Status,
			&i.GrantedVia,
			&i.GrantedAt,
			&i.RevokedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeConsentGrant = `-- name: RevokeConsentGrant :one
UPDATE consent_grants
SET status = 'revoked', revoked_at = now()
WHERE id = $1 AND patient_id = $2 AND status = 'active'
RETURNING id, patient_id, grantee_type, grantee_id, scope, scope_ref, status, granted_via, granted_at, revoked_at, expires_at
`

type RevokeConsentGrantParams struct {
	ID        pgtype.UUID `json:"id"`
	PatientID pgtype.UUID `json:"patient_id"`
}

func (q *Queries) RevokeConsentGrant(ctx context.Context, arg RevokeConsentGrantParams) (ConsentGrant, error) {
	row := q.db.QueryRow(ctx, revokeConsentGrant, arg.ID, arg.PatientID)
	var i ConsentGrant
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.GranteeType,
		&i.GranteeID,
		&i.Scope,
		&i.ScopeRef,
		&i.Status,
		&i.GrantedVia,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.ExpiresAt,
	)
	return i, err
}
