// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facilities.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFacilities = `-- name: CountFacilities :one
SELECT count(*) FROM facilities
`

func (q *Queries) CountFacilities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFacilities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFacility = `-- name: CreateFacility :one
INSERT INTO facilities (name, type, region, district, phone, address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, type, region, district, phone, address, created_at, updated_at
`

type CreateFacilityParams struct {
	Name     string       `json:"name"`
	Type     FacilityType `json:"type"`
	Region   pgtype.Text  `json:"region"`
	District pgtype.Text  `json:"district"`
	Phone    pgtype.Text  `json:"phone"`
	Address  pgtype.Text  `json:"address"`
}

func (q *Queries) CreateFacility(ctx context.Context, arg CreateFacilityParams) (Facility, error) {
	row := q.db.QueryRow(ctx, createFacility,
		arg.Name,
		arg.Type,
		arg.Region,
		arg.District,
		arg.Phone,
		arg.Address,
	)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Region,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (user_id, facility_id, specialty, license_number)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, facility_id, specialty, license_number, created_at, updated_at
`

type CreateProviderParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	FacilityID    pgtype.UUID `json:"facility_id"`
	Specialty     pgtype.Text `json:"specialty"`
	LicenseNumber pgtype.Text `json:"license_number"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.UserID,
		arg.FacilityID,
		arg.Specialty,
		arg.LicenseNumber,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacilityID,
		&i.Specialty,
		&i.LicenseNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findFacilityByID = `-- name: FindFacilityByID :one
SELECT id, name, type, region, district, phone, address, created_at, updated_at FROM facilities WHERE id = $1
`

func (q *Queries) FindFacilityByID(ctx context.Context, id pgtype.UUID) (Facility, error) {
	row := q.db.QueryRow(ctx, findFacilityByID, id)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Region,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findProviderByUserID = `-- name: FindProviderByUserID :one
SELECT id, user_id, facility_id, specialty, license_number, created_at, updated_at FROM providers WHERE user_id = $1
`

func (q *Queries) FindProviderByUserID(ctx context.Context, userID pgtype.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, findProviderByUserID, userID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacilityID,
		&i.Specialty,
		&i.LicenseNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFacilities = `-- name: ListFacilities :many
SELECT id, name, type, region, district, phone, address, created_at, updated_at FROM facilities ORDER BY name
`

func (q *Queries) ListFacilities(ctx context.Context) ([]Facility, error) {
	rows, err := q.db.Query(ctx, listFacilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Facility
	for rows.Next() {
		var i Facility
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Region,
			&i.District,
			&i.Phone,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
