// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: facilities.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countFacilities = `-- name: CountFacilities :one
SELECT count(*) FROM facilities
`

func (q *Queries) CountFacilities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFacilities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBranch = `-- name: CreateBranch :one
INSERT INTO branches (facility_id, name, address, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, facility_id, name, address, phone, created_at, updated_at
`

type CreateBranchParams struct {
	FacilityID pgtype.UUID `json:"facility_id"`
	Name       string      `json:"name"`
	Address    pgtype.Text `json:"address"`
	Phone      pgtype.Text `json:"phone"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, createBranch,
		arg.FacilityID,
		arg.Name,
		arg.Address,
		arg.Phone,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (facility_id, name)
VALUES ($1, $2)
RETURNING id, facility_id, name, created_at, updated_at
`

type CreateDepartmentParams struct {
	FacilityID pgtype.UUID `json:"facility_id"`
	Name       string      `json:"name"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment, arg.FacilityID, arg.Name)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFacility = `-- name: CreateFacility :one
INSERT INTO facilities (name, type, region, district, phone, address)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, name, type, region, district, phone, address, created_at, updated_at, logo_url, working_hours, referral_policies
`

type CreateFacilityParams struct {
	Name     string       `json:"name"`
	Type     FacilityType `json:"type"`
	Region   pgtype.Text  `json:"region"`
	District pgtype.Text  `json:"district"`
	Phone    pgtype.Text  `json:"phone"`
	Address  pgtype.Text  `json:"address"`
}

func (q *Queries) CreateFacility(ctx context.Context, arg CreateFacilityParams) (Facility, error) {
	row := q.db.QueryRow(ctx, createFacility,
		arg.Name,
		arg.Type,
		arg.Region,
		arg.District,
		arg.Phone,
		arg.Address,
	)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Region,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
		&i.WorkingHours,
		&i.ReferralPolicies,
	)
	return i, err
}

const createProvider = `-- name: CreateProvider :one
INSERT INTO providers (user_id, facility_id, specialty, license_number)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, facility_id, specialty, license_number, created_at, updated_at, qualifications, years_experience, consultation_fee, verification_status, languages, certificates, areas_of_expertise
`

type CreateProviderParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	FacilityID    pgtype.UUID `json:"facility_id"`
	Specialty     pgtype.Text `json:"specialty"`
	LicenseNumber pgtype.Text `json:"license_number"`
}

func (q *Queries) CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error) {
	row := q.db.QueryRow(ctx, createProvider,
		arg.UserID,
		arg.FacilityID,
		arg.Specialty,
		arg.LicenseNumber,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacilityID,
		&i.Specialty,
		&i.LicenseNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Qualifications,
		&i.YearsExperience,
		&i.ConsultationFee,
		&i.VerificationStatus,
		&i.Languages,
		&i.Certificates,
		&i.AreasOfExpertise,
	)
	return i, err
}

const deleteBranch = `-- name: DeleteBranch :exec
DELETE FROM branches WHERE id = $1
`

func (q *Queries) DeleteBranch(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBranch, id)
	return err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDepartment, id)
	return err
}

const findBranchByID = `-- name: FindBranchByID :one
SELECT id, facility_id, name, address, phone, created_at, updated_at FROM branches WHERE id = $1
`

func (q *Queries) FindBranchByID(ctx context.Context, id pgtype.UUID) (Branch, error) {
	row := q.db.QueryRow(ctx, findBranchByID, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findDepartmentByID = `-- name: FindDepartmentByID :one
SELECT id, facility_id, name, created_at, updated_at FROM departments WHERE id = $1
`

func (q *Queries) FindDepartmentByID(ctx context.Context, id pgtype.UUID) (Department, error) {
	row := q.db.QueryRow(ctx, findDepartmentByID, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findFacilityByID = `-- name: FindFacilityByID :one
SELECT id, name, type, region, district, phone, address, created_at, updated_at, logo_url, working_hours, referral_policies FROM facilities WHERE id = $1
`

func (q *Queries) FindFacilityByID(ctx context.Context, id pgtype.UUID) (Facility, error) {
	row := q.db.QueryRow(ctx, findFacilityByID, id)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Region,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
		&i.WorkingHours,
		&i.ReferralPolicies,
	)
	return i, err
}

const findProviderByID = `-- name: FindProviderByID :one
SELECT id, user_id, facility_id, specialty, license_number, created_at, updated_at, qualifications, years_experience, consultation_fee, verification_status, languages, certificates, areas_of_expertise FROM providers WHERE id = $1
`

func (q *Queries) FindProviderByID(ctx context.Context, id pgtype.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, findProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacilityID,
		&i.Specialty,
		&i.LicenseNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Qualifications,
		&i.YearsExperience,
		&i.ConsultationFee,
		&i.VerificationStatus,
		&i.Languages,
		&i.Certificates,
		&i.AreasOfExpertise,
	)
	return i, err
}

const findProviderByUserID = `-- name: FindProviderByUserID :one
SELECT id, user_id, facility_id, specialty, license_number, created_at, updated_at, qualifications, years_experience, consultation_fee, verification_status, languages, certificates, areas_of_expertise FROM providers WHERE user_id = $1
`

func (q *Queries) FindProviderByUserID(ctx context.Context, userID pgtype.UUID) (Provider, error) {
	row := q.db.QueryRow(ctx, findProviderByUserID, userID)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacilityID,
		&i.Specialty,
		&i.LicenseNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Qualifications,
		&i.YearsExperience,
		&i.ConsultationFee,
		&i.VerificationStatus,
		&i.Languages,
		&i.Certificates,
		&i.AreasOfExpertise,
	)
	return i, err
}

const listBranchesByFacility = `-- name: ListBranchesByFacility :many
SELECT id, facility_id, name, address, phone, created_at, updated_at FROM branches WHERE facility_id = $1 ORDER BY name
`

func (q *Queries) ListBranchesByFacility(ctx context.Context, facilityID pgtype.UUID) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranchesByFacility, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Branch
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.Name,
			&i.Address,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartmentsByFacility = `-- name: ListDepartmentsByFacility :many
SELECT id, facility_id, name, created_at, updated_at FROM departments WHERE facility_id = $1 ORDER BY name
`

func (q *Queries) ListDepartmentsByFacility(ctx context.Context, facilityID pgtype.UUID) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartmentsByFacility, facilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.FacilityID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFacilities = `-- name: ListFacilities :many
SELECT id, name, type, region, district, phone, address, created_at, updated_at, logo_url, working_hours, referral_policies FROM facilities ORDER BY name
`

func (q *Queries) ListFacilities(ctx context.Context) ([]Facility, error) {
	rows, err := q.db.Query(ctx, listFacilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Facility
	for rows.Next() {
		var i Facility
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Region,
			&i.District,
			&i.Phone,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogoUrl,
			&i.WorkingHours,
			&i.ReferralPolicies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchFacilities = `-- name: SearchFacilities :many
SELECT id, name, type, region, district, phone, address, created_at, updated_at, logo_url, working_hours, referral_policies FROM facilities
WHERE name ILIKE '%' || $1::text || '%'
ORDER BY similarity(name, $1::text) DESC, name
LIMIT $2::int
`

type SearchFacilitiesParams struct {
	Query       string `json:"query"`
	ResultLimit int32  `json:"result_limit"`
}

// Directory-style search, open to any authenticated user (no sensitive
// data on a facility's name/region/district) — see search.Service.Search.
func (q *Queries) SearchFacilities(ctx context.Context, arg SearchFacilitiesParams) ([]Facility, error) {
	rows, err := q.db.Query(ctx, searchFacilities, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Facility
	for rows.Next() {
		var i Facility
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Region,
			&i.District,
			&i.Phone,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LogoUrl,
			&i.WorkingHours,
			&i.ReferralPolicies,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProviders = `-- name: SearchProviders :many
SELECT p.id, p.user_id, p.facility_id, p.specialty, p.license_number, p.created_at, p.updated_at, p.qualifications, p.years_experience, p.consultation_fee, p.verification_status, p.languages, p.certificates, p.areas_of_expertise, u.full_name AS user_full_name FROM providers p
JOIN users u ON u.id = p.user_id
WHERE u.full_name ILIKE '%' || $1::text || '%'
   OR p.specialty ILIKE '%' || $1::text || '%'
ORDER BY similarity(coalesce(u.full_name, ''), $1::text) DESC, u.full_name
LIMIT $2::int
`

type SearchProvidersParams struct {
	Query       string `json:"query"`
	ResultLimit int32  `json:"result_limit"`
}

type SearchProvidersRow struct {
	ID                 pgtype.UUID        `json:"id"`
	UserID             pgtype.UUID        `json:"user_id"`
	FacilityID         pgtype.UUID        `json:"facility_id"`
	Specialty          pgtype.Text        `json:"specialty"`
	LicenseNumber      pgtype.Text        `json:"license_number"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Qualifications     []string           `json:"qualifications"`
	YearsExperience    pgtype.Int4        `json:"years_experience"`
	ConsultationFee    pgtype.Numeric     `json:"consultation_fee"`
	VerificationStatus string             `json:"verification_status"`
	Languages          []string           `json:"languages"`
	Certificates       []byte             `json:"certificates"`
	AreasOfExpertise   []string           `json:"areas_of_expertise"`
	UserFullName       pgtype.Text        `json:"user_full_name"`
}

// Directory-style doctor search by the user's full_name or the provider's
// specialty — open to any authenticated user, same reasoning as
// SearchFacilities. Joins users only to read full_name; no other
// user fields are exposed.
func (q *Queries) SearchProviders(ctx context.Context, arg SearchProvidersParams) ([]SearchProvidersRow, error) {
	rows, err := q.db.Query(ctx, searchProviders, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProvidersRow
	for rows.Next() {
		var i SearchProvidersRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FacilityID,
			&i.Specialty,
			&i.LicenseNumber,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Qualifications,
			&i.YearsExperience,
			&i.ConsultationFee,
			&i.VerificationStatus,
			&i.Languages,
			&i.Certificates,
			&i.AreasOfExpertise,
			&i.UserFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :one
UPDATE branches
SET name = $2, address = $3, phone = $4, updated_at = now()
WHERE id = $1
RETURNING id, facility_id, name, address, phone, created_at, updated_at
`

type UpdateBranchParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Address pgtype.Text `json:"address"`
	Phone   pgtype.Text `json:"phone"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) (Branch, error) {
	row := q.db.QueryRow(ctx, updateBranch,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.Phone,
	)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Name,
		&i.Address,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET name = $2, updated_at = now()
WHERE id = $1
RETURNING id, facility_id, name, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment, arg.ID, arg.Name)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.FacilityID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateFacilityLogoAndHours = `-- name: UpdateFacilityLogoAndHours :one
UPDATE facilities
SET logo_url = $2, working_hours = $3, referral_policies = $4, updated_at = now()
WHERE id = $1
RETURNING id, name, type, region, district, phone, address, created_at, updated_at, logo_url, working_hours, referral_policies
`

type UpdateFacilityLogoAndHoursParams struct {
	ID               pgtype.UUID `json:"id"`
	LogoUrl          pgtype.Text `json:"logo_url"`
	WorkingHours     []byte      `json:"working_hours"`
	ReferralPolicies pgtype.Text `json:"referral_policies"`
}

func (q *Queries) UpdateFacilityLogoAndHours(ctx context.Context, arg UpdateFacilityLogoAndHoursParams) (Facility, error) {
	row := q.db.QueryRow(ctx, updateFacilityLogoAndHours,
		arg.ID,
		arg.LogoUrl,
		arg.WorkingHours,
		arg.ReferralPolicies,
	)
	var i Facility
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Region,
		&i.District,
		&i.Phone,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LogoUrl,
		&i.WorkingHours,
		&i.ReferralPolicies,
	)
	return i, err
}

const updateProviderProfile = `-- name: UpdateProviderProfile :one
UPDATE providers
SET qualifications = $2,
    years_experience = $3,
    consultation_fee = $4,
    languages = $5,
    certificates = $6,
    areas_of_expertise = $7,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, facility_id, specialty, license_number, created_at, updated_at, qualifications, years_experience, consultation_fee, verification_status, languages, certificates, areas_of_expertise
`

type UpdateProviderProfileParams struct {
	ID               pgtype.UUID    `json:"id"`
	Qualifications   []string       `json:"qualifications"`
	YearsExperience  pgtype.Int4    `json:"years_experience"`
	ConsultationFee  pgtype.Numeric `json:"consultation_fee"`
	Languages        []string       `json:"languages"`
	Certificates     []byte         `json:"certificates"`
	AreasOfExpertise []string       `json:"areas_of_expertise"`
}

// Self-editable provider profile fields. Deliberately excludes
// verification_status (admin-only, see UpdateProviderVerificationStatus)
// and specialty/license_number (set at creation, not editable via this
// profile-update surface).
func (q *Queries) UpdateProviderProfile(ctx context.Context, arg UpdateProviderProfileParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderProfile,
		arg.ID,
		arg.Qualifications,
		arg.YearsExperience,
		arg.ConsultationFee,
		arg.Languages,
		arg.Certificates,
		arg.AreasOfExpertise,
	)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacilityID,
		&i.Specialty,
		&i.LicenseNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Qualifications,
		&i.YearsExperience,
		&i.ConsultationFee,
		&i.VerificationStatus,
		&i.Languages,
		&i.Certificates,
		&i.AreasOfExpertise,
	)
	return i, err
}

const updateProviderVerificationStatus = `-- name: UpdateProviderVerificationStatus :one
UPDATE providers
SET verification_status = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, facility_id, specialty, license_number, created_at, updated_at, qualifications, years_experience, consultation_fee, verification_status, languages, certificates, areas_of_expertise
`

type UpdateProviderVerificationStatusParams struct {
	ID                 pgtype.UUID `json:"id"`
	VerificationStatus string      `json:"verification_status"`
}

// Admin-only field, kept as its own query so the self-edit path
// (UpdateProviderProfile) can never touch it.
func (q *Queries) UpdateProviderVerificationStatus(ctx context.Context, arg UpdateProviderVerificationStatusParams) (Provider, error) {
	row := q.db.QueryRow(ctx, updateProviderVerificationStatus, arg.ID, arg.VerificationStatus)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FacilityID,
		&i.Specialty,
		&i.LicenseNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Qualifications,
		&i.YearsExperience,
		&i.ConsultationFee,
		&i.VerificationStatus,
		&i.Languages,
		&i.Certificates,
		&i.AreasOfExpertise,
	)
	return i, err
}
