// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feature_flags.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listFeatureFlags = `-- name: ListFeatureFlags :many
SELECT key, enabled, description, updated_at FROM feature_flags ORDER BY key
`

func (q *Queries) ListFeatureFlags(ctx context.Context) ([]FeatureFlag, error) {
	rows, err := q.db.Query(ctx, listFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeatureFlag
	for rows.Next() {
		var i FeatureFlag
		if err := rows.Scan(
			&i.Key,
			&i.Enabled,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFeatureFlag = `-- name: UpsertFeatureFlag :one
INSERT INTO feature_flags (key, enabled, description)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET enabled = excluded.enabled,
    description = COALESCE(excluded.description, feature_flags.description),
    updated_at = now()
RETURNING key, enabled, description, updated_at
`

type UpsertFeatureFlagParams struct {
	Key         string      `json:"key"`
	Enabled     bool        `json:"enabled"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpsertFeatureFlag(ctx context.Context, arg UpsertFeatureFlagParams) (FeatureFlag, error) {
	row := q.db.QueryRow(ctx, upsertFeatureFlag, arg.Key, arg.Enabled, arg.Description)
	var i FeatureFlag
	err := row.Scan(
		&i.Key,
		&i.Enabled,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}
