// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messaging.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addConversationMember = `-- name: AddConversationMember :exec
INSERT INTO conversation_members (conversation_id, user_id)
VALUES ($1, $2)
`

type AddConversationMemberParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error {
	_, err := q.db.Exec(ctx, addConversationMember, arg.ConversationID, arg.UserID)
	return err
}

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (type, created_by)
VALUES ($1, $2)
RETURNING id, type, created_by, created_at, updated_at
`

type CreateConversationParams struct {
	Type      ConversationType `json:"type"`
	CreatedBy pgtype.UUID      `json:"created_by"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.Type, arg.CreatedBy)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (conversation_id, sender_id, body, attachment_ids)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, sender_id, body, attachment_ids, created_at
`

type CreateMessageParams struct {
	ConversationID pgtype.UUID   `json:"conversation_id"`
	SenderID       pgtype.UUID   `json:"sender_id"`
	Body           string        `json:"body"`
	AttachmentIds  []pgtype.UUID `json:"attachment_ids"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ConversationID,
		arg.SenderID,
		arg.Body,
		arg.AttachmentIds,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderID,
		&i.Body,
		&i.AttachmentIds,
		&i.CreatedAt,
	)
	return i, err
}

const findConversationMember = `-- name: FindConversationMember :one
SELECT conversation_id, user_id, last_read_at, joined_at FROM conversation_members WHERE conversation_id = $1 AND user_id = $2
`

type FindConversationMemberParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) FindConversationMember(ctx context.Context, arg FindConversationMemberParams) (ConversationMember, error) {
	row := q.db.QueryRow(ctx, findConversationMember, arg.ConversationID, arg.UserID)
	var i ConversationMember
	err := row.Scan(
		&i.ConversationID,
		&i.UserID,
		&i.LastReadAt,
		&i.JoinedAt,
	)
	return i, err
}

const findDirectConversationBetween = `-- name: FindDirectConversationBetween :one
SELECT c.id, c.type, c.created_by, c.created_at, c.updated_at FROM conversations c
WHERE c.type = 'direct'
  AND EXISTS (SELECT 1 FROM conversation_members m1 WHERE m1.conversation_id = c.id AND m1.user_id = $1)
  AND EXISTS (SELECT 1 FROM conversation_members m2 WHERE m2.conversation_id = c.id AND m2.user_id = $2)
  AND (SELECT count(*) FROM conversation_members m WHERE m.conversation_id = c.id) = 2
LIMIT 1
`

type FindDirectConversationBetweenParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

// De-duplicates direct conversations — reuse the existing 1:1 conversation
// between two users instead of creating a new one every time.
func (q *Queries) FindDirectConversationBetween(ctx context.Context, arg FindDirectConversationBetweenParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, findDirectConversationBetween, arg.UserID, arg.UserID_2)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversationMembers = `-- name: ListConversationMembers :many
SELECT conversation_id, user_id, last_read_at, joined_at FROM conversation_members WHERE conversation_id = $1
`

func (q *Queries) ListConversationMembers(ctx context.Context, conversationID pgtype.UUID) ([]ConversationMember, error) {
	rows, err := q.db.Query(ctx, listConversationMembers, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationMember
	for rows.Next() {
		var i ConversationMember
		if err := rows.Scan(
			&i.ConversationID,
			&i.UserID,
			&i.LastReadAt,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationsForUser = `-- name: ListConversationsForUser :many
SELECT
    c.id, c.type, c.created_by, c.created_at, c.updated_at,
    m.last_read_at AS caller_last_read_at,
    lm.body AS last_message_body,
    lm.created_at AS last_message_at,
    other.user_id AS other_user_id
FROM conversations c
JOIN conversation_members m ON m.conversation_id = c.id AND m.user_id = $1
LEFT JOIN LATERAL (
    SELECT body, created_at FROM messages WHERE conversation_id = c.id ORDER BY created_at DESC LIMIT 1
) lm ON true
LEFT JOIN LATERAL (
    SELECT user_id FROM conversation_members WHERE conversation_id = c.id AND user_id != $1 LIMIT 1
) other ON true
ORDER BY c.updated_at DESC
`

type ListConversationsForUserRow struct {
	ID               pgtype.UUID        `json:"id"`
	Type             ConversationType   `json:"type"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CallerLastReadAt pgtype.Timestamptz `json:"caller_last_read_at"`
	LastMessageBody  string             `json:"last_message_body"`
	LastMessageAt    pgtype.Timestamptz `json:"last_message_at"`
	OtherUserID      pgtype.UUID        `json:"other_user_id"`
}

// Includes a last-message preview via LATERAL join so the conversation list
// can show it without N+1 queries. Also surfaces the caller's own
// last_read_at (via the join condition, m is always the caller's own
// membership row) and, for direct conversations, the other member's user_id
// (via another LATERAL join) so the UI has someone to label the thread
// with instead of just created_by, which is meaningless when the caller
// didn't create it.
func (q *Queries) ListConversationsForUser(ctx context.Context, userID pgtype.UUID) ([]ListConversationsForUserRow, error) {
	rows, err := q.db.Query(ctx, listConversationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsForUserRow
	for rows.Next() {
		var i ListConversationsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CallerLastReadAt,
			&i.LastMessageBody,
			&i.LastMessageAt,
			&i.OtherUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMessages = `-- name: ListRecentMessages :many
SELECT id, conversation_id, sender_id, body, attachment_ids, created_at FROM (
    SELECT id, conversation_id, sender_id, body, attachment_ids, created_at FROM messages WHERE conversation_id = $1 ORDER BY created_at DESC LIMIT 200
) recent ORDER BY created_at ASC
`

// Returns the most recent 200 messages oldest-first: the inner query picks
// the latest 200 by created_at DESC, then the outer query re-orders that
// subset ascending. Plain "ORDER BY created_at ASC LIMIT 200" would instead
// return the OLDEST 200 messages, which is wrong for a chat history view.
func (q *Queries) ListRecentMessages(ctx context.Context, conversationID pgtype.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listRecentMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderID,
			&i.Body,
			&i.AttachmentIds,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markConversationRead = `-- name: MarkConversationRead :exec
UPDATE conversation_members SET last_read_at = now() WHERE conversation_id = $1 AND user_id = $2
`

type MarkConversationReadParams struct {
	ConversationID pgtype.UUID `json:"conversation_id"`
	UserID         pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) error {
	_, err := q.db.Exec(ctx, markConversationRead, arg.ConversationID, arg.UserID)
	return err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchConversation(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchConversation, id)
	return err
}
