// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuditResult string

const (
	AuditResultAllowed AuditResult = "allowed"
	AuditResultDenied  AuditResult = "denied"
)

func (e *AuditResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuditResult(s)
	case string:
		*e = AuditResult(s)
	default:
		return fmt.Errorf("unsupported scan type for AuditResult: %T", src)
	}
	return nil
}

type NullAuditResult struct {
	AuditResult AuditResult `json:"audit_result"`
	Valid       bool        `json:"valid"` // Valid is true if AuditResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuditResult) Scan(value interface{}) error {
	if value == nil {
		ns.AuditResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuditResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuditResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuditResult), nil
}

type ConsentGrantedVia string

const (
	ConsentGrantedViaPatientExplicit          ConsentGrantedVia = "patient_explicit"
	ConsentGrantedViaReferralImpliedTemporary ConsentGrantedVia = "referral_implied_temporary"
	ConsentGrantedViaProviderCreated          ConsentGrantedVia = "provider_created"
)

func (e *ConsentGrantedVia) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentGrantedVia(s)
	case string:
		*e = ConsentGrantedVia(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentGrantedVia: %T", src)
	}
	return nil
}

type NullConsentGrantedVia struct {
	ConsentGrantedVia ConsentGrantedVia `json:"consent_granted_via"`
	Valid             bool              `json:"valid"` // Valid is true if ConsentGrantedVia is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentGrantedVia) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentGrantedVia, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentGrantedVia.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentGrantedVia) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentGrantedVia), nil
}

type ConsentGranteeType string

const (
	ConsentGranteeTypeProvider ConsentGranteeType = "provider"
	ConsentGranteeTypeFacility ConsentGranteeType = "facility"
)

func (e *ConsentGranteeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentGranteeType(s)
	case string:
		*e = ConsentGranteeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentGranteeType: %T", src)
	}
	return nil
}

type NullConsentGranteeType struct {
	ConsentGranteeType ConsentGranteeType `json:"consent_grantee_type"`
	Valid              bool               `json:"valid"` // Valid is true if ConsentGranteeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentGranteeType) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentGranteeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentGranteeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentGranteeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentGranteeType), nil
}

type ConsentScope string

const (
	ConsentScopeFullRecord   ConsentScope = "full_record"
	ConsentScopeReferralOnly ConsentScope = "referral_only"
)

func (e *ConsentScope) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentScope(s)
	case string:
		*e = ConsentScope(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentScope: %T", src)
	}
	return nil
}

type NullConsentScope struct {
	ConsentScope ConsentScope `json:"consent_scope"`
	Valid        bool         `json:"valid"` // Valid is true if ConsentScope is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentScope) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentScope, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentScope.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentScope) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentScope), nil
}

type ConsentStatus string

const (
	ConsentStatusActive  ConsentStatus = "active"
	ConsentStatusRevoked ConsentStatus = "revoked"
)

func (e *ConsentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConsentStatus(s)
	case string:
		*e = ConsentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConsentStatus: %T", src)
	}
	return nil
}

type NullConsentStatus struct {
	ConsentStatus ConsentStatus `json:"consent_status"`
	Valid         bool          `json:"valid"` // Valid is true if ConsentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConsentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConsentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConsentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConsentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConsentStatus), nil
}

type EncounterType string

const (
	EncounterTypeReferral     EncounterType = "referral"
	EncounterTypeConsult      EncounterType = "consult"
	EncounterTypeGeneralVisit EncounterType = "general_visit"
)

func (e *EncounterType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EncounterType(s)
	case string:
		*e = EncounterType(s)
	default:
		return fmt.Errorf("unsupported scan type for EncounterType: %T", src)
	}
	return nil
}

type NullEncounterType struct {
	EncounterType EncounterType `json:"encounter_type"`
	Valid         bool          `json:"valid"` // Valid is true if EncounterType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEncounterType) Scan(value interface{}) error {
	if value == nil {
		ns.EncounterType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EncounterType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEncounterType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EncounterType), nil
}

type FacilityType string

const (
	FacilityTypeHospital FacilityType = "hospital"
	FacilityTypeClinic   FacilityType = "clinic"
	FacilityTypeLab      FacilityType = "lab"
	FacilityTypePharmacy FacilityType = "pharmacy"
	FacilityTypeInsurer  FacilityType = "insurer"
)

func (e *FacilityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FacilityType(s)
	case string:
		*e = FacilityType(s)
	default:
		return fmt.Errorf("unsupported scan type for FacilityType: %T", src)
	}
	return nil
}

type NullFacilityType struct {
	FacilityType FacilityType `json:"facility_type"`
	Valid        bool         `json:"valid"` // Valid is true if FacilityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFacilityType) Scan(value interface{}) error {
	if value == nil {
		ns.FacilityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FacilityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFacilityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FacilityType), nil
}

type ObservationType string

const (
	ObservationTypeVitals     ObservationType = "vitals"
	ObservationTypeDiagnosis  ObservationType = "diagnosis"
	ObservationTypeNote       ObservationType = "note"
	ObservationTypeAttachment ObservationType = "attachment"
)

func (e *ObservationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ObservationType(s)
	case string:
		*e = ObservationType(s)
	default:
		return fmt.Errorf("unsupported scan type for ObservationType: %T", src)
	}
	return nil
}

type NullObservationType struct {
	ObservationType ObservationType `json:"observation_type"`
	Valid           bool            `json:"valid"` // Valid is true if ObservationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullObservationType) Scan(value interface{}) error {
	if value == nil {
		ns.ObservationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ObservationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullObservationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ObservationType), nil
}

type ReferralStatus string

const (
	ReferralStatusCreated    ReferralStatus = "created"
	ReferralStatusRouted     ReferralStatus = "routed"
	ReferralStatusAccepted   ReferralStatus = "accepted"
	ReferralStatusDeclined   ReferralStatus = "declined"
	ReferralStatusInProgress ReferralStatus = "in_progress"
	ReferralStatusCompleted  ReferralStatus = "completed"
	ReferralStatusCancelled  ReferralStatus = "cancelled"
)

func (e *ReferralStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReferralStatus(s)
	case string:
		*e = ReferralStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReferralStatus: %T", src)
	}
	return nil
}

type NullReferralStatus struct {
	ReferralStatus ReferralStatus `json:"referral_status"`
	Valid          bool           `json:"valid"` // Valid is true if ReferralStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReferralStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReferralStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReferralStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReferralStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReferralStatus), nil
}

type ReferralUrgency string

const (
	ReferralUrgencyRoutine   ReferralUrgency = "routine"
	ReferralUrgencyUrgent    ReferralUrgency = "urgent"
	ReferralUrgencyEmergency ReferralUrgency = "emergency"
)

func (e *ReferralUrgency) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReferralUrgency(s)
	case string:
		*e = ReferralUrgency(s)
	default:
		return fmt.Errorf("unsupported scan type for ReferralUrgency: %T", src)
	}
	return nil
}

type NullReferralUrgency struct {
	ReferralUrgency ReferralUrgency `json:"referral_urgency"`
	Valid           bool            `json:"valid"` // Valid is true if ReferralUrgency is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReferralUrgency) Scan(value interface{}) error {
	if value == nil {
		ns.ReferralUrgency, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReferralUrgency.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReferralUrgency) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReferralUrgency), nil
}

type UserRole string

const (
	UserRolePatient       UserRole = "patient"
	UserRolePhysician     UserRole = "physician"
	UserRoleHospitalAdmin UserRole = "hospital_admin"
	UserRoleLabTech       UserRole = "lab_tech"
	UserRolePharmacist    UserRole = "pharmacist"
	UserRoleInsurer       UserRole = "insurer"
	UserRoleSystemAdmin   UserRole = "system_admin"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type AuditLog struct {
	ID           pgtype.UUID        `json:"id"`
	ActorUserID  pgtype.UUID        `json:"actor_user_id"`
	ActorRole    UserRole           `json:"actor_role"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	PatientID    pgtype.UUID        `json:"patient_id"`
	Result       AuditResult        `json:"result"`
	Metadata     []byte             `json:"metadata"`
	OccurredAt   pgtype.Timestamptz `json:"occurred_at"`
}

type ClinicalObservation struct {
	ID          pgtype.UUID        `json:"id"`
	EncounterID pgtype.UUID        `json:"encounter_id"`
	Type        ObservationType    `json:"type"`
	Payload     []byte             `json:"payload"`
	RecordedBy  pgtype.UUID        `json:"recorded_by"`
	RecordedAt  pgtype.Timestamptz `json:"recorded_at"`
}

type ConsentGrant struct {
	ID          pgtype.UUID        `json:"id"`
	PatientID   pgtype.UUID        `json:"patient_id"`
	GranteeType ConsentGranteeType `json:"grantee_type"`
	GranteeID   pgtype.UUID        `json:"grantee_id"`
	Scope       ConsentScope       `json:"scope"`
	ScopeRef    pgtype.UUID        `json:"scope_ref"`
	Status      ConsentStatus      `json:"status"`
	GrantedVia  ConsentGrantedVia  `json:"granted_via"`
	GrantedAt   pgtype.Timestamptz `json:"granted_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type Encounter struct {
	ID         pgtype.UUID        `json:"id"`
	PatientID  pgtype.UUID        `json:"patient_id"`
	FacilityID pgtype.UUID        `json:"facility_id"`
	ProviderID pgtype.UUID        `json:"provider_id"`
	Type       EncounterType      `json:"type"`
	Notes      pgtype.Text        `json:"notes"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
	Version    int32              `json:"version"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Facility struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Type      FacilityType       `json:"type"`
	Region    pgtype.Text        `json:"region"`
	District  pgtype.Text        `json:"district"`
	Phone     pgtype.Text        `json:"phone"`
	Address   pgtype.Text        `json:"address"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Patient struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	FullName    string             `json:"full_name"`
	DateOfBirth pgtype.Date        `json:"date_of_birth"`
	Sex         pgtype.Text        `json:"sex"`
	NationalID  pgtype.Text        `json:"national_id"`
	Phone       pgtype.Text        `json:"phone"`
	Address     pgtype.Text        `json:"address"`
	NextOfKin   pgtype.Text        `json:"next_of_kin"`
	Version     int32              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Permission struct {
	ID       pgtype.UUID `json:"id"`
	Resource string      `json:"resource"`
	Action   string      `json:"action"`
}

type Provider struct {
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	FacilityID    pgtype.UUID        `json:"facility_id"`
	Specialty     pgtype.Text        `json:"specialty"`
	LicenseNumber pgtype.Text        `json:"license_number"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Referral struct {
	ID                         pgtype.UUID        `json:"id"`
	PatientID                  pgtype.UUID        `json:"patient_id"`
	ReferringProviderID        pgtype.UUID        `json:"referring_provider_id"`
	ReferringFacilityID        pgtype.UUID        `json:"referring_facility_id"`
	ReceivingFacilityID        pgtype.UUID        `json:"receiving_facility_id"`
	ReceivingProviderID        pgtype.UUID        `json:"receiving_provider_id"`
	SpecialtyRequested         string             `json:"specialty_requested"`
	Urgency                    ReferralUrgency    `json:"urgency"`
	Status                     ReferralStatus     `json:"status"`
	Reason                     string             `json:"reason"`
	ClinicalSummaryEncounterID pgtype.UUID        `json:"clinical_summary_encounter_id"`
	Version                    int32              `json:"version"`
	CreatedAt                  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                  pgtype.Timestamptz `json:"updated_at"`
}

type ReferralStatusEvent struct {
	ID          pgtype.UUID        `json:"id"`
	ReferralID  pgtype.UUID        `json:"referral_id"`
	FromStatus  NullReferralStatus `json:"from_status"`
	ToStatus    ReferralStatus     `json:"to_status"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Note        pgtype.Text        `json:"note"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

type Role struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	FullAccess  bool               `json:"full_access"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RolePermission struct {
	RoleID       pgtype.UUID `json:"role_id"`
	PermissionID pgtype.UUID `json:"permission_id"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Phone        pgtype.Text        `json:"phone"`
	PasswordHash string             `json:"password_hash"`
	Role         UserRole           `json:"role"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	RoleID       pgtype.UUID        `json:"role_id"`
}
