// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (user_id, type, payload)
VALUES ($1, $2, $3)
RETURNING id, user_id, type, payload, read_at, created_at
`

type CreateNotificationParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Type    string      `json:"type"`
	Payload []byte      `json:"payload"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification, arg.UserID, arg.Type, arg.Payload)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Payload,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationPreferences = `-- name: GetNotificationPreferences :many
SELECT user_id, channel, enabled FROM notification_preferences WHERE user_id = $1
`

func (q *Queries) GetNotificationPreferences(ctx context.Context, userID pgtype.UUID) ([]NotificationPreference, error) {
	rows, err := q.db.Query(ctx, getNotificationPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationPreference
	for rows.Next() {
		var i NotificationPreference
		if err := rows.Scan(&i.UserID, &i.Channel, &i.Enabled); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationsForUser = `-- name: ListNotificationsForUser :many
SELECT id, user_id, type, payload, read_at, created_at FROM notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListNotificationsForUser(ctx context.Context, userID pgtype.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotificationsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.Payload,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read_at = now() WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, userID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read_at = now() WHERE id = $1 AND user_id = $2 AND read_at IS NULL
`

type MarkNotificationReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.Exec(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const upsertNotificationPreference = `-- name: UpsertNotificationPreference :one
INSERT INTO notification_preferences (user_id, channel, enabled)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, channel) DO UPDATE SET enabled = excluded.enabled
RETURNING user_id, channel, enabled
`

type UpsertNotificationPreferenceParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Channel string      `json:"channel"`
	Enabled bool        `json:"enabled"`
}

func (q *Queries) UpsertNotificationPreference(ctx context.Context, arg UpsertNotificationPreferenceParams) (NotificationPreference, error) {
	row := q.db.QueryRow(ctx, upsertNotificationPreference, arg.UserID, arg.Channel, arg.Enabled)
	var i NotificationPreference
	err := row.Scan(&i.UserID, &i.Channel, &i.Enabled)
	return i, err
}
