// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, photo_url, bio, languages, availability_status, is_online, last_seen_at, created_at, updated_at
FROM user_profiles
WHERE user_id = $1
`

func (q *Queries) GetUserProfile(ctx context.Context, userID pgtype.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.PhotoUrl,
		&i.Bio,
		&i.Languages,
		&i.AvailabilityStatus,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setUserProfilePresence = `-- name: SetUserProfilePresence :exec
INSERT INTO user_profiles (user_id, is_online, last_seen_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE
SET is_online = EXCLUDED.is_online,
    last_seen_at = EXCLUDED.last_seen_at,
    updated_at = now()
`

type SetUserProfilePresenceParams struct {
	UserID     pgtype.UUID        `json:"user_id"`
	IsOnline   bool               `json:"is_online"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) SetUserProfilePresence(ctx context.Context, arg SetUserProfilePresenceParams) error {
	_, err := q.db.Exec(ctx, setUserProfilePresence, arg.UserID, arg.IsOnline, arg.LastSeenAt)
	return err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profiles (user_id, bio, languages, availability_status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
SET bio = EXCLUDED.bio,
    languages = EXCLUDED.languages,
    availability_status = EXCLUDED.availability_status,
    updated_at = now()
RETURNING user_id, photo_url, bio, languages, availability_status, is_online, last_seen_at, created_at, updated_at
`

type UpsertUserProfileParams struct {
	UserID             pgtype.UUID `json:"user_id"`
	Bio                pgtype.Text `json:"bio"`
	Languages          []string    `json:"languages"`
	AvailabilityStatus pgtype.Text `json:"availability_status"`
}

// Partial update semantics live in the repository (Go), not here: the
// repository always re-reads-then-writes the merged bio/languages/
// availability_status, so this query itself is a plain full upsert.
func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.UserID,
		arg.Bio,
		arg.Languages,
		arg.AvailabilityStatus,
	)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.PhotoUrl,
		&i.Bio,
		&i.Languages,
		&i.AvailabilityStatus,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserProfilePhoto = `-- name: UpsertUserProfilePhoto :one
INSERT INTO user_profiles (user_id, photo_url)
VALUES ($1, $2)
ON CONFLICT (user_id) DO UPDATE
SET photo_url = EXCLUDED.photo_url,
    updated_at = now()
RETURNING user_id, photo_url, bio, languages, availability_status, is_online, last_seen_at, created_at, updated_at
`

type UpsertUserProfilePhotoParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	PhotoUrl pgtype.Text `json:"photo_url"`
}

func (q *Queries) UpsertUserProfilePhoto(ctx context.Context, arg UpsertUserProfilePhotoParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfilePhoto, arg.UserID, arg.PhotoUrl)
	var i UserProfile
	err := row.Scan(
		&i.UserID,
		&i.PhotoUrl,
		&i.Bio,
		&i.Languages,
		&i.AvailabilityStatus,
		&i.IsOnline,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
