// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptReferral(ctx context.Context, arg AcceptReferralParams) (Referral, error)
	CreateClinicalObservation(ctx context.Context, arg CreateClinicalObservationParams) (ClinicalObservation, error)
	CreateConsentGrant(ctx context.Context, arg CreateConsentGrantParams) (ConsentGrant, error)
	CreateEncounter(ctx context.Context, arg CreateEncounterParams) (Encounter, error)
	CreateFacility(ctx context.Context, arg CreateFacilityParams) (Facility, error)
	CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error)
	CreateProvider(ctx context.Context, arg CreateProviderParams) (Provider, error)
	CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error)
	CreateReferralStatusEvent(ctx context.Context, arg CreateReferralStatusEventParams) (ReferralStatusEvent, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindActiveGrants(ctx context.Context, arg FindActiveGrantsParams) ([]ConsentGrant, error)
	FindEncounterByID(ctx context.Context, id pgtype.UUID) (Encounter, error)
	FindFacilityByID(ctx context.Context, id pgtype.UUID) (Facility, error)
	FindPatientByID(ctx context.Context, id pgtype.UUID) (Patient, error)
	FindProviderByUserID(ctx context.Context, userID pgtype.UUID) (Provider, error)
	FindReferralByID(ctx context.Context, id pgtype.UUID) (Referral, error)
	FindUserByEmailOrPhone(ctx context.Context, email pgtype.Text) (User, error)
	FindUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) (AuditLog, error)
	ListAuditLogForPatient(ctx context.Context, patientID pgtype.UUID) ([]AuditLog, error)
	ListConsentGrantsForPatient(ctx context.Context, patientID pgtype.UUID) ([]ConsentGrant, error)
	ListEncountersByPatient(ctx context.Context, patientID pgtype.UUID) ([]Encounter, error)
	ListFacilities(ctx context.Context) ([]Facility, error)
	ListObservationsByEncounter(ctx context.Context, encounterID pgtype.UUID) ([]ClinicalObservation, error)
	ListReferralStatusEvents(ctx context.Context, referralID pgtype.UUID) ([]ReferralStatusEvent, error)
	ListReferralsByPatient(ctx context.Context, patientID pgtype.UUID) ([]Referral, error)
	ListReferralsForFacility(ctx context.Context, receivingFacilityID pgtype.UUID) ([]Referral, error)
	RevokeConsentGrant(ctx context.Context, arg RevokeConsentGrantParams) (ConsentGrant, error)
	UpdateReferralStatus(ctx context.Context, arg UpdateReferralStatusParams) (Referral, error)
}

var _ Querier = (*Queries)(nil)
