// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createClinicalObservation = `-- name: CreateClinicalObservation :one
INSERT INTO clinical_observations (encounter_id, type, payload, recorded_by)
VALUES ($1, $2, $3, $4)
RETURNING id, encounter_id, type, payload, recorded_by, recorded_at
`

type CreateClinicalObservationParams struct {
	EncounterID pgtype.UUID     `json:"encounter_id"`
	Type        ObservationType `json:"type"`
	Payload     []byte          `json:"payload"`
	RecordedBy  pgtype.UUID     `json:"recorded_by"`
}

func (q *Queries) CreateClinicalObservation(ctx context.Context, arg CreateClinicalObservationParams) (ClinicalObservation, error) {
	row := q.db.QueryRow(ctx, createClinicalObservation,
		arg.EncounterID,
		arg.Type,
		arg.Payload,
		arg.RecordedBy,
	)
	var i ClinicalObservation
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Type,
		&i.Payload,
		&i.RecordedBy,
		&i.RecordedAt,
	)
	return i, err
}

const createEncounter = `-- name: CreateEncounter :one
INSERT INTO encounters (patient_id, facility_id, provider_id, type, notes, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, patient_id, facility_id, provider_id, type, notes, occurred_at, version, created_at, updated_at
`

type CreateEncounterParams struct {
	PatientID  pgtype.UUID        `json:"patient_id"`
	FacilityID pgtype.UUID        `json:"facility_id"`
	ProviderID pgtype.UUID        `json:"provider_id"`
	Type       EncounterType      `json:"type"`
	Notes      pgtype.Text        `json:"notes"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateEncounter(ctx context.Context, arg CreateEncounterParams) (Encounter, error) {
	row := q.db.QueryRow(ctx, createEncounter,
		arg.PatientID,
		arg.FacilityID,
		arg.ProviderID,
		arg.Type,
		arg.Notes,
		arg.OccurredAt,
	)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.FacilityID,
		&i.ProviderID,
		&i.Type,
		&i.Notes,
		&i.OccurredAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (user_id, full_name, date_of_birth, sex, national_id, phone, address, next_of_kin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, full_name, date_of_birth, sex, national_id, phone, address, next_of_kin, version, created_at, updated_at
`

type CreatePatientParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	FullName    string      `json:"full_name"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Sex         pgtype.Text `json:"sex"`
	NationalID  pgtype.Text `json:"national_id"`
	Phone       pgtype.Text `json:"phone"`
	Address     pgtype.Text `json:"address"`
	NextOfKin   pgtype.Text `json:"next_of_kin"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.UserID,
		arg.FullName,
		arg.DateOfBirth,
		arg.Sex,
		arg.NationalID,
		arg.Phone,
		arg.Address,
		arg.NextOfKin,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Sex,
		&i.NationalID,
		&i.Phone,
		&i.Address,
		&i.NextOfKin,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findEncounterByID = `-- name: FindEncounterByID :one
SELECT id, patient_id, facility_id, provider_id, type, notes, occurred_at, version, created_at, updated_at FROM encounters WHERE id = $1
`

func (q *Queries) FindEncounterByID(ctx context.Context, id pgtype.UUID) (Encounter, error) {
	row := q.db.QueryRow(ctx, findEncounterByID, id)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.FacilityID,
		&i.ProviderID,
		&i.Type,
		&i.Notes,
		&i.OccurredAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPatientByID = `-- name: FindPatientByID :one
SELECT id, user_id, full_name, date_of_birth, sex, national_id, phone, address, next_of_kin, version, created_at, updated_at FROM patients WHERE id = $1
`

func (q *Queries) FindPatientByID(ctx context.Context, id pgtype.UUID) (Patient, error) {
	row := q.db.QueryRow(ctx, findPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Sex,
		&i.NationalID,
		&i.Phone,
		&i.Address,
		&i.NextOfKin,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEncountersByPatient = `-- name: ListEncountersByPatient :many
SELECT id, patient_id, facility_id, provider_id, type, notes, occurred_at, version, created_at, updated_at FROM encounters WHERE patient_id = $1 ORDER BY occurred_at DESC
`

func (q *Queries) ListEncountersByPatient(ctx context.Context, patientID pgtype.UUID) ([]Encounter, error) {
	rows, err := q.db.Query(ctx, listEncountersByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Encounter
	for rows.Next() {
		var i Encounter
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.FacilityID,
			&i.ProviderID,
			&i.Type,
			&i.Notes,
			&i.OccurredAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByEncounter = `-- name: ListObservationsByEncounter :many
SELECT id, encounter_id, type, payload, recorded_by, recorded_at FROM clinical_observations WHERE encounter_id = $1 ORDER BY recorded_at
`

func (q *Queries) ListObservationsByEncounter(ctx context.Context, encounterID pgtype.UUID) ([]ClinicalObservation, error) {
	rows, err := q.db.Query(ctx, listObservationsByEncounter, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClinicalObservation
	for rows.Next() {
		var i ClinicalObservation
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.Type,
			&i.Payload,
			&i.RecordedBy,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
