// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEncounters = `-- name: CountEncounters :one
SELECT count(*) FROM encounters
`

func (q *Queries) CountEncounters(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEncounters)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPatients = `-- name: CountPatients :one
SELECT count(*) FROM patients
`

func (q *Queries) CountPatients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPatients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClinicalObservation = `-- name: CreateClinicalObservation :one
INSERT INTO clinical_observations (encounter_id, type, payload, recorded_by)
VALUES ($1, $2, $3, $4)
RETURNING id, encounter_id, type, payload, recorded_by, recorded_at
`

type CreateClinicalObservationParams struct {
	EncounterID pgtype.UUID     `json:"encounter_id"`
	Type        ObservationType `json:"type"`
	Payload     []byte          `json:"payload"`
	RecordedBy  pgtype.UUID     `json:"recorded_by"`
}

func (q *Queries) CreateClinicalObservation(ctx context.Context, arg CreateClinicalObservationParams) (ClinicalObservation, error) {
	row := q.db.QueryRow(ctx, createClinicalObservation,
		arg.EncounterID,
		arg.Type,
		arg.Payload,
		arg.RecordedBy,
	)
	var i ClinicalObservation
	err := row.Scan(
		&i.ID,
		&i.EncounterID,
		&i.Type,
		&i.Payload,
		&i.RecordedBy,
		&i.RecordedAt,
	)
	return i, err
}

const createEncounter = `-- name: CreateEncounter :one
INSERT INTO encounters (patient_id, facility_id, provider_id, type, notes, occurred_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, patient_id, facility_id, provider_id, type, notes, occurred_at, version, created_at, updated_at
`

type CreateEncounterParams struct {
	PatientID  pgtype.UUID        `json:"patient_id"`
	FacilityID pgtype.UUID        `json:"facility_id"`
	ProviderID pgtype.UUID        `json:"provider_id"`
	Type       EncounterType      `json:"type"`
	Notes      pgtype.Text        `json:"notes"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) CreateEncounter(ctx context.Context, arg CreateEncounterParams) (Encounter, error) {
	row := q.db.QueryRow(ctx, createEncounter,
		arg.PatientID,
		arg.FacilityID,
		arg.ProviderID,
		arg.Type,
		arg.Notes,
		arg.OccurredAt,
	)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.FacilityID,
		&i.ProviderID,
		&i.Type,
		&i.Notes,
		&i.OccurredAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPatient = `-- name: CreatePatient :one
INSERT INTO patients (user_id, full_name, date_of_birth, sex, national_id, phone, address, next_of_kin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, full_name, date_of_birth, sex, national_id, phone, address, next_of_kin, version, created_at, updated_at, gender, blood_group
`

type CreatePatientParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	FullName    string      `json:"full_name"`
	DateOfBirth pgtype.Date `json:"date_of_birth"`
	Sex         pgtype.Text `json:"sex"`
	NationalID  pgtype.Text `json:"national_id"`
	Phone       pgtype.Text `json:"phone"`
	Address     pgtype.Text `json:"address"`
	NextOfKin   pgtype.Text `json:"next_of_kin"`
}

func (q *Queries) CreatePatient(ctx context.Context, arg CreatePatientParams) (Patient, error) {
	row := q.db.QueryRow(ctx, createPatient,
		arg.UserID,
		arg.FullName,
		arg.DateOfBirth,
		arg.Sex,
		arg.NationalID,
		arg.Phone,
		arg.Address,
		arg.NextOfKin,
	)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Sex,
		&i.NationalID,
		&i.Phone,
		&i.Address,
		&i.NextOfKin,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.BloodGroup,
	)
	return i, err
}

const findEncounterByID = `-- name: FindEncounterByID :one
SELECT id, patient_id, facility_id, provider_id, type, notes, occurred_at, version, created_at, updated_at FROM encounters WHERE id = $1
`

func (q *Queries) FindEncounterByID(ctx context.Context, id pgtype.UUID) (Encounter, error) {
	row := q.db.QueryRow(ctx, findEncounterByID, id)
	var i Encounter
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.FacilityID,
		&i.ProviderID,
		&i.Type,
		&i.Notes,
		&i.OccurredAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPatientByID = `-- name: FindPatientByID :one
SELECT id, user_id, full_name, date_of_birth, sex, national_id, phone, address, next_of_kin, version, created_at, updated_at, gender, blood_group FROM patients WHERE id = $1
`

func (q *Queries) FindPatientByID(ctx context.Context, id pgtype.UUID) (Patient, error) {
	row := q.db.QueryRow(ctx, findPatientByID, id)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Sex,
		&i.NationalID,
		&i.Phone,
		&i.Address,
		&i.NextOfKin,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.BloodGroup,
	)
	return i, err
}

const findPatientMedicalHistoryByPatientID = `-- name: FindPatientMedicalHistoryByPatientID :one
SELECT id, patient_id, allergies, chronic_conditions, current_medications, past_surgeries, family_history, vaccination_history, updated_by, created_at, updated_at FROM patient_medical_history WHERE patient_id = $1
`

// Returns pgx.ErrNoRows if no row exists yet — expected (a patient with no
// medical history recorded), handled in the repository layer, not an error
// condition.
func (q *Queries) FindPatientMedicalHistoryByPatientID(ctx context.Context, patientID pgtype.UUID) (PatientMedicalHistory, error) {
	row := q.db.QueryRow(ctx, findPatientMedicalHistoryByPatientID, patientID)
	var i PatientMedicalHistory
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Allergies,
		&i.ChronicConditions,
		&i.CurrentMedications,
		&i.PastSurgeries,
		&i.FamilyHistory,
		&i.VaccinationHistory,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEncountersByPatient = `-- name: ListEncountersByPatient :many
SELECT id, patient_id, facility_id, provider_id, type, notes, occurred_at, version, created_at, updated_at FROM encounters WHERE patient_id = $1 ORDER BY occurred_at DESC
`

func (q *Queries) ListEncountersByPatient(ctx context.Context, patientID pgtype.UUID) ([]Encounter, error) {
	rows, err := q.db.Query(ctx, listEncountersByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Encounter
	for rows.Next() {
		var i Encounter
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.FacilityID,
			&i.ProviderID,
			&i.Type,
			&i.Notes,
			&i.OccurredAt,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObservationsByEncounter = `-- name: ListObservationsByEncounter :many
SELECT id, encounter_id, type, payload, recorded_by, recorded_at FROM clinical_observations WHERE encounter_id = $1 ORDER BY recorded_at
`

func (q *Queries) ListObservationsByEncounter(ctx context.Context, encounterID pgtype.UUID) ([]ClinicalObservation, error) {
	rows, err := q.db.Query(ctx, listObservationsByEncounter, encounterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClinicalObservation
	for rows.Next() {
		var i ClinicalObservation
		if err := rows.Scan(
			&i.ID,
			&i.EncounterID,
			&i.Type,
			&i.Payload,
			&i.RecordedBy,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPatients = `-- name: ListPatients :many
SELECT id, user_id, full_name, date_of_birth, sex, national_id, phone, address, next_of_kin, version, created_at, updated_at, gender, blood_group FROM patients ORDER BY created_at DESC
`

func (q *Queries) ListPatients(ctx context.Context) ([]Patient, error) {
	rows, err := q.db.Query(ctx, listPatients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Patient
	for rows.Next() {
		var i Patient
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.DateOfBirth,
			&i.Sex,
			&i.NationalID,
			&i.Phone,
			&i.Address,
			&i.NextOfKin,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Gender,
			&i.BloodGroup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePatientGenderBloodGroup = `-- name: UpdatePatientGenderBloodGroup :one
UPDATE patients
SET gender = $2,
    blood_group = $3,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, full_name, date_of_birth, sex, national_id, phone, address, next_of_kin, version, created_at, updated_at, gender, blood_group
`

type UpdatePatientGenderBloodGroupParams struct {
	ID         pgtype.UUID `json:"id"`
	Gender     pgtype.Text `json:"gender"`
	BloodGroup pgtype.Text `json:"blood_group"`
}

func (q *Queries) UpdatePatientGenderBloodGroup(ctx context.Context, arg UpdatePatientGenderBloodGroupParams) (Patient, error) {
	row := q.db.QueryRow(ctx, updatePatientGenderBloodGroup, arg.ID, arg.Gender, arg.BloodGroup)
	var i Patient
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Sex,
		&i.NationalID,
		&i.Phone,
		&i.Address,
		&i.NextOfKin,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Gender,
		&i.BloodGroup,
	)
	return i, err
}

const upsertPatientMedicalHistory = `-- name: UpsertPatientMedicalHistory :one
INSERT INTO patient_medical_history (
    patient_id, allergies, chronic_conditions, current_medications,
    past_surgeries, family_history, vaccination_history, updated_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (patient_id) DO UPDATE
SET allergies = EXCLUDED.allergies,
    chronic_conditions = EXCLUDED.chronic_conditions,
    current_medications = EXCLUDED.current_medications,
    past_surgeries = EXCLUDED.past_surgeries,
    family_history = EXCLUDED.family_history,
    vaccination_history = EXCLUDED.vaccination_history,
    updated_by = EXCLUDED.updated_by,
    updated_at = now()
RETURNING id, patient_id, allergies, chronic_conditions, current_medications, past_surgeries, family_history, vaccination_history, updated_by, created_at, updated_at
`

type UpsertPatientMedicalHistoryParams struct {
	PatientID          pgtype.UUID `json:"patient_id"`
	Allergies          []byte      `json:"allergies"`
	ChronicConditions  []byte      `json:"chronic_conditions"`
	CurrentMedications []byte      `json:"current_medications"`
	PastSurgeries      []byte      `json:"past_surgeries"`
	FamilyHistory      []byte      `json:"family_history"`
	VaccinationHistory []byte      `json:"vaccination_history"`
	UpdatedBy          pgtype.UUID `json:"updated_by"`
}

// Always a full replacement of all six jsonb columns (plus updated_by) —
// no partial-update merge here, unlike UpsertUserProfile. See
// Service.UpdateMedicalHistory.
func (q *Queries) UpsertPatientMedicalHistory(ctx context.Context, arg UpsertPatientMedicalHistoryParams) (PatientMedicalHistory, error) {
	row := q.db.QueryRow(ctx, upsertPatientMedicalHistory,
		arg.PatientID,
		arg.Allergies,
		arg.ChronicConditions,
		arg.CurrentMedications,
		arg.PastSurgeries,
		arg.FamilyHistory,
		arg.VaccinationHistory,
		arg.UpdatedBy,
	)
	var i PatientMedicalHistory
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Allergies,
		&i.ChronicConditions,
		&i.CurrentMedications,
		&i.PastSurgeries,
		&i.FamilyHistory,
		&i.VaccinationHistory,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
