// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: referrals.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptReferral = `-- name: AcceptReferral :one
UPDATE referrals
SET status = 'accepted', receiving_provider_id = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $2 AND status = 'routed'
RETURNING id, patient_id, referring_provider_id, referring_facility_id, receiving_facility_id, receiving_provider_id, specialty_requested, urgency, status, reason, clinical_summary_encounter_id, version, created_at, updated_at
`

type AcceptReferralParams struct {
	ID                  pgtype.UUID `json:"id"`
	Version             int32       `json:"version"`
	ReceivingProviderID pgtype.UUID `json:"receiving_provider_id"`
}

func (q *Queries) AcceptReferral(ctx context.Context, arg AcceptReferralParams) (Referral, error) {
	row := q.db.QueryRow(ctx, acceptReferral, arg.ID, arg.Version, arg.ReceivingProviderID)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ReferringProviderID,
		&i.ReferringFacilityID,
		&i.ReceivingFacilityID,
		&i.ReceivingProviderID,
		&i.SpecialtyRequested,
		&i.Urgency,
		&i.Status,
		&i.Reason,
		&i.ClinicalSummaryEncounterID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReferral = `-- name: CreateReferral :one
INSERT INTO referrals (
    patient_id, referring_provider_id, referring_facility_id, receiving_facility_id,
    specialty_requested, urgency, reason, clinical_summary_encounter_id, status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'routed')
RETURNING id, patient_id, referring_provider_id, referring_facility_id, receiving_facility_id, receiving_provider_id, specialty_requested, urgency, status, reason, clinical_summary_encounter_id, version, created_at, updated_at
`

type CreateReferralParams struct {
	PatientID                  pgtype.UUID     `json:"patient_id"`
	ReferringProviderID        pgtype.UUID     `json:"referring_provider_id"`
	ReferringFacilityID        pgtype.UUID     `json:"referring_facility_id"`
	ReceivingFacilityID        pgtype.UUID     `json:"receiving_facility_id"`
	SpecialtyRequested         string          `json:"specialty_requested"`
	Urgency                    ReferralUrgency `json:"urgency"`
	Reason                     string          `json:"reason"`
	ClinicalSummaryEncounterID pgtype.UUID     `json:"clinical_summary_encounter_id"`
}

func (q *Queries) CreateReferral(ctx context.Context, arg CreateReferralParams) (Referral, error) {
	row := q.db.QueryRow(ctx, createReferral,
		arg.PatientID,
		arg.ReferringProviderID,
		arg.ReferringFacilityID,
		arg.ReceivingFacilityID,
		arg.SpecialtyRequested,
		arg.Urgency,
		arg.Reason,
		arg.ClinicalSummaryEncounterID,
	)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ReferringProviderID,
		&i.ReferringFacilityID,
		&i.ReceivingFacilityID,
		&i.ReceivingProviderID,
		&i.SpecialtyRequested,
		&i.Urgency,
		&i.Status,
		&i.Reason,
		&i.ClinicalSummaryEncounterID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createReferralStatusEvent = `-- name: CreateReferralStatusEvent :one
INSERT INTO referral_status_events (referral_id, from_status, to_status, actor_user_id, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, referral_id, from_status, to_status, actor_user_id, note, occurred_at
`

type CreateReferralStatusEventParams struct {
	ReferralID  pgtype.UUID        `json:"referral_id"`
	FromStatus  NullReferralStatus `json:"from_status"`
	ToStatus    ReferralStatus     `json:"to_status"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Note        pgtype.Text        `json:"note"`
}

func (q *Queries) CreateReferralStatusEvent(ctx context.Context, arg CreateReferralStatusEventParams) (ReferralStatusEvent, error) {
	row := q.db.QueryRow(ctx, createReferralStatusEvent,
		arg.ReferralID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorUserID,
		arg.Note,
	)
	var i ReferralStatusEvent
	err := row.Scan(
		&i.ID,
		&i.ReferralID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ActorUserID,
		&i.Note,
		&i.OccurredAt,
	)
	return i, err
}

const findReferralByID = `-- name: FindReferralByID :one
SELECT id, patient_id, referring_provider_id, referring_facility_id, receiving_facility_id, receiving_provider_id, specialty_requested, urgency, status, reason, clinical_summary_encounter_id, version, created_at, updated_at FROM referrals WHERE id = $1
`

func (q *Queries) FindReferralByID(ctx context.Context, id pgtype.UUID) (Referral, error) {
	row := q.db.QueryRow(ctx, findReferralByID, id)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ReferringProviderID,
		&i.ReferringFacilityID,
		&i.ReceivingFacilityID,
		&i.ReceivingProviderID,
		&i.SpecialtyRequested,
		&i.Urgency,
		&i.Status,
		&i.Reason,
		&i.ClinicalSummaryEncounterID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReferralStatusEvents = `-- name: ListReferralStatusEvents :many
SELECT id, referral_id, from_status, to_status, actor_user_id, note, occurred_at FROM referral_status_events WHERE referral_id = $1 ORDER BY occurred_at
`

func (q *Queries) ListReferralStatusEvents(ctx context.Context, referralID pgtype.UUID) ([]ReferralStatusEvent, error) {
	rows, err := q.db.Query(ctx, listReferralStatusEvents, referralID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReferralStatusEvent
	for rows.Next() {
		var i ReferralStatusEvent
		if err := rows.Scan(
			&i.ID,
			&i.ReferralID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorUserID,
			&i.Note,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralsByPatient = `-- name: ListReferralsByPatient :many
SELECT id, patient_id, referring_provider_id, referring_facility_id, receiving_facility_id, receiving_provider_id, specialty_requested, urgency, status, reason, clinical_summary_encounter_id, version, created_at, updated_at FROM referrals WHERE patient_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReferralsByPatient(ctx context.Context, patientID pgtype.UUID) ([]Referral, error) {
	rows, err := q.db.Query(ctx, listReferralsByPatient, patientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Referral
	for rows.Next() {
		var i Referral
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.ReferringProviderID,
			&i.ReferringFacilityID,
			&i.ReceivingFacilityID,
			&i.ReceivingProviderID,
			&i.SpecialtyRequested,
			&i.Urgency,
			&i.Status,
			&i.Reason,
			&i.ClinicalSummaryEncounterID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReferralsForFacility = `-- name: ListReferralsForFacility :many
SELECT id, patient_id, referring_provider_id, referring_facility_id, receiving_facility_id, receiving_provider_id, specialty_requested, urgency, status, reason, clinical_summary_encounter_id, version, created_at, updated_at FROM referrals WHERE receiving_facility_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListReferralsForFacility(ctx context.Context, receivingFacilityID pgtype.UUID) ([]Referral, error) {
	rows, err := q.db.Query(ctx, listReferralsForFacility, receivingFacilityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Referral
	for rows.Next() {
		var i Referral
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.ReferringProviderID,
			&i.ReferringFacilityID,
			&i.ReceivingFacilityID,
			&i.ReceivingProviderID,
			&i.SpecialtyRequested,
			&i.Urgency,
			&i.Status,
			&i.Reason,
			&i.ClinicalSummaryEncounterID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReferralStatus = `-- name: UpdateReferralStatus :one
UPDATE referrals
SET status = $3, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $2
RETURNING id, patient_id, referring_provider_id, referring_facility_id, receiving_facility_id, receiving_provider_id, specialty_requested, urgency, status, reason, clinical_summary_encounter_id, version, created_at, updated_at
`

type UpdateReferralStatusParams struct {
	ID      pgtype.UUID    `json:"id"`
	Version int32          `json:"version"`
	Status  ReferralStatus `json:"status"`
}

func (q *Queries) UpdateReferralStatus(ctx context.Context, arg UpdateReferralStatusParams) (Referral, error) {
	row := q.db.QueryRow(ctx, updateReferralStatus, arg.ID, arg.Version, arg.Status)
	var i Referral
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.ReferringProviderID,
		&i.ReferringFacilityID,
		&i.ReceivingFacilityID,
		&i.ReceivingProviderID,
		&i.SpecialtyRequested,
		&i.Urgency,
		&i.Status,
		&i.Reason,
		&i.ClinicalSummaryEncounterID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
