// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSavedSearch = `-- name: CreateSavedSearch :one
INSERT INTO saved_searches (user_id, name, query, filters)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, query, filters, created_at
`

type CreateSavedSearchParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Name    string      `json:"name"`
	Query   string      `json:"query"`
	Filters []byte      `json:"filters"`
}

func (q *Queries) CreateSavedSearch(ctx context.Context, arg CreateSavedSearchParams) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, createSavedSearch,
		arg.UserID,
		arg.Name,
		arg.Query,
		arg.Filters,
	)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Query,
		&i.Filters,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSavedSearch = `-- name: DeleteSavedSearch :execrows
DELETE FROM saved_searches WHERE id = $1 AND user_id = $2
`

type DeleteSavedSearchParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteSavedSearch(ctx context.Context, arg DeleteSavedSearchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSavedSearch, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findSavedSearchByID = `-- name: FindSavedSearchByID :one
SELECT id, user_id, name, query, filters, created_at FROM saved_searches WHERE id = $1
`

func (q *Queries) FindSavedSearchByID(ctx context.Context, id pgtype.UUID) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, findSavedSearchByID, id)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Query,
		&i.Filters,
		&i.CreatedAt,
	)
	return i, err
}

const listSavedSearchesForUser = `-- name: ListSavedSearchesForUser :many
SELECT id, user_id, name, query, filters, created_at FROM saved_searches WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSavedSearchesForUser(ctx context.Context, userID pgtype.UUID) ([]SavedSearch, error) {
	rows, err := q.db.Query(ctx, listSavedSearchesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SavedSearch
	for rows.Next() {
		var i SavedSearch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Query,
			&i.Filters,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
